In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('Files/homepricesmulti.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
import math
# retorna o maior numero inteiro menor ou igual a x(mediana nesse caso)
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [11]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
reg = linear_model.LinearRegression()
# (variaveis iindependetes, variaveis dependentes)
reg.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression()

In [15]:
reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [16]:
reg.intercept_

array([221323.0018654])

In [17]:
reg.predict([[300,3,40]])

C:\Users\Win10\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[195839.65833654]])

In [18]:
reg.predict([[2500,4,5]])

C:\Users\Win10\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[578876.03748933]])

In [22]:
pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=8b20c9a4e49971c0f7a7c09e7ea94118df0c069a54a2eb62147648f3d809ddbe
  Stored in directory: c:\users\win10\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [23]:
df = pd.read_csv('Files/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [32]:
df['experience'] = df['experience'].fillna('0')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
from word2number import w2n

In [34]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [35]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [37]:
test_score_median = math.floor(df['test_score(out of 10)'].median())

In [39]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score_median)

In [40]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [44]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])

LinearRegression()

In [45]:
reg.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [46]:
reg.intercept_

array([17737.26346434])

In [48]:
reg.predict([[2,9,6]])

C:\Users\Win10\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53205.96797671]])

In [55]:
new_row = {'experience': 2,'test_score(out of 10)': 9,'interview_score(out of 10)': 6,'salary($)': 53205}
df = df.append(new_row, ignore_index=True)
df

C:\Users\Win10\AppData\Local\Temp\ipykernel_9688\3466596038.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000
8           2                    9.0                           6      53205
9           2                    9.0                           6      53205

In [56]:
df = df.drop(9)

In [57]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000
8           2                    9.0                           6      53205

In [59]:
reg.predict([[12,10,10]])

C:\Users\Win10\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[92002.18340611]])

In [61]:
new_row = {'experience': 12,'test_score(out of 10)': 10,'interview_score(out of 10)': 10,'salary($)': 92002}
df = df.append(new_row, ignore_index=True)

C:\Users\Win10\AppData\Local\Temp\ipykernel_9688\3731837396.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)


In [62]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000
8           2                    9.0                           6      53205
9          12                   10.0                          10      92002

In [63]:
df_sorted = df.sort_values(by='salary($)', ascending=False)

In [64]:
df_sorted

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
9          12                   10.0                          10      92002
7          11                    7.0                           8      80000
6          10                    8.0                           7      72000
4           7                    9.0                           6      70000
3           2                   10.0                          10      65000
5           3                    7.0                          10      62000
2           5                    6.0                           7      60000
8           2                    9.0                           6      53205
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.